In [1]:
# import the dependencies

import pandas as pd

In [12]:
dataset=pd.read_csv("Resources/column_2C_weka.csv")
dataset.head()

,pelvic_incidence,pelvic_tilt numeric,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,class
0,63.027817,22.552586,39.609117,40.475232,98.672917,-0.254400,Abnormal
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,Abnormal
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,Abnormal
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,Abnormal
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,Abnormal

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pelvic_incidence          310 non-null    float64
 1   pelvic_tilt numeric       310 non-null    float64
 2   lumbar_lordosis_angle     310 non-null    float64
 3   sacral_slope              310 non-null    float64
 4   pelvic_radius             310 non-null    float64
 5   degree_spondylolisthesis  310 non-null    float64
 6   class                     310 non-null    object
dtypes: float64(6), object(1)
memory usage: 17.1+ KB

In [14]:
dataset.columns

Index(['pelvic_incidence', 'pelvic_tilt numeric', 'lumbar_lordosis_angle',
       'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'class'],
      dtype='object')

In [17]:
dataset=dataset.rename(columns={"pelvic_incidence":"Pelvic Incidence",
                                "pelvic_tilt numeric":"Pelvic Tilt",
                                "lumbar_lordosis_angle":"Lumbar Lordosis Angle",
                                "sacral_slope":"Sacral Slope",
                                "pelvic_radius":"Pelvic Radius",
                                "degree_spondylolisthesis":"Grade of spondylolisthesis",
                                "class":"Results"})
dataset.head()

,Pelvic Incidence,Pelvic Tilt,Lumbar Lordosis Angle,Sacral Slope,Pelvic Radius,Grade of spondylolisthesis,Results
0,63.03,22.552586,39.609117,40.475232,98.672917,-0.254400,Abnormal
1,39.06,10.060991,25.015378,28.995960,114.405425,4.564259,Abnormal
2,68.83,22.218482,50.092194,46.613539,105.985135,-3.530317,Abnormal
3,69.30,24.652878,44.311238,44.644130,101.868495,11.211523,Abnormal
4,49.71,9.652075,28.317406,40.060784,108.168725,7.918501,Abnormal

In [18]:
dataset["Pelvic Incidence"]=round(dataset["Pelvic Incidence"],2)
dataset.head()

,Pelvic Incidence,Pelvic Tilt,Lumbar Lordosis Angle,Sacral Slope,Pelvic Radius,Grade of spondylolisthesis,Results
0,63.03,22.552586,39.609117,40.475232,98.672917,-0.254400,Abnormal
1,39.06,10.060991,25.015378,28.995960,114.405425,4.564259,Abnormal
2,68.83,22.218482,50.092194,46.613539,105.985135,-3.530317,Abnormal
3,69.30,24.652878,44.311238,44.644130,101.868495,11.211523,Abnormal
4,49.71,9.652075,28.317406,40.060784,108.168725,7.918501,Abnormal

In [19]:
dataset["Pelvic Tilt"]=round(dataset["Pelvic Tilt"],2)
dataset["Lumbar Lordosis Angle"]=round(dataset["Lumbar Lordosis Angle"],2)
dataset["Sacral Slope"]=round(dataset["Sacral Slope"],2)
dataset["Pelvic Radius"]=round(dataset["Pelvic Radius"],2)
dataset["Grade of spondylolisthesis"]=round(dataset["Grade of spondylolisthesis"],2)
dataset.head()

,Pelvic Incidence,Pelvic Tilt,Lumbar Lordosis Angle,Sacral Slope,Pelvic Radius,Grade of spondylolisthesis,Results
0,63.03,22.55,39.61,40.48,98.67,-0.25,Abnormal
1,39.06,10.06,25.02,29.00,114.41,4.56,Abnormal
2,68.83,22.22,50.09,46.61,105.99,-3.53,Abnormal
3,69.30,24.65,44.31,44.64,101.87,11.21,Abnormal
4,49.71,9.65,28.32,40.06,108.17,7.92,Abnormal

In [20]:
dataset.to_csv("Resources/dataset_clean.csv",index=False)